### ISSUE TITLE
How to remove the directory in the repository

### ISSUE THREAD

**Issue by holmofy** [LasyIsLazy/github-upload-action#1]
My workflow is like this，There is a file in this path: `./starter/target/openapi.yaml`
```yaml
  - name: Upload to GitHub
    uses: LasyIsLazy/github-upload-action@v0.0.2
    with:
      access-token: ${{ secrets.REPO_ACCESS_TOKEN }}
      file-path: ./starter/target/openapi.yaml
      username: DouTiao-Tech
      repo: apollo-marketing-api
      commit-message: ${{github.event.inputs.message}}
```
But the directory I got from repo is structured like this:
```sh
/-
 |--starter
    |--target
        |--openapi.yaml
```
I expect `openapi.yaml` to be placed in the root directory. how should I do.
